<?php

namespace SparQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-24 at 15:28:31.
 */
class ConnectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers SparQL\Connection::ns
     * @todo   Implement testNs().
     */
    public function testNs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::errno
     * @todo   Implement testErrno().
     */
    public function testErrno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::error
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::cgiParams
     * @todo   Implement testCgiParams().
     */
    public function testCgiParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::alive
     * @todo   Implement testAlive().
     */
    public function testAlive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::dispatchQuery
     * @todo   Implement testDispatchQuery().
     */
    public function testDispatchQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::capabilityCache
     * @todo   Implement testCapabilityCache().
     */
    public function testCapabilityCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::capabilityCodes
     * @todo   Implement testCapabilityCodes().
     */
    public function testCapabilityCodes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::capabilityDescription
     * @todo   Implement testCapabilityDescription().
     */
    public function testCapabilityDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::supports
     * @todo   Implement testSupports().
     */
    public function testSupports()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::anySubject
     * @todo   Implement testAnySubject().
     */
    public function testAnySubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testSelect
     * @todo   Implement testTestSelect().
     */
    public function testTestSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testMathAs
     * @todo   Implement testTestMathAs().
     */
    public function testTestMathAs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testConstantAs
     * @todo   Implement testTestConstantAs().
     */
    public function testTestConstantAs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testCount
     * @todo   Implement testTestCount().
     */
    public function testTestCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testMax
     * @todo   Implement testTestMax().
     */
    public function testTestMax()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testSample
     * @todo   Implement testTestSample().
     */
    public function testTestSample()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\Connection::testLoad
     * @todo   Implement testTestLoad().
     */
    public function testTestLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
