<?php

namespace SparQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-24 at 15:28:31.
 */
class ParseXmlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ParseXml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ParseXml('file://' . __DIR__ . '/sample.rdf', 'url');

        echo $this->object->parse();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers SparQL\ParseXml::error
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\ParseXml::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\ParseXml::startXML
     * @todo   Implement testStartXML().
     */
    public function testStartXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\ParseXml::endXML
     * @todo   Implement testEndXML().
     */
    public function testEndXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SparQL\ParseXml::charXML
     * @todo   Implement testCharXML().
     */
    public function testCharXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
